### ISSUE TITLE
Support multiple node?

### ISSUE THREAD

**Issue by ErrorDoc404** [brblacky/lavalink-status#5]
can it support multiple node ? if yes may I know how?

**Comment by LucasB25** [comment]
It only supports node 16

**Comment by ErrorDoc404** [comment]
i am asking if it support multiple lava link node at one?

**Comment by Gremagol** [comment]
Yes it does

**Comment by Gremagol** [comment]
Also Node v17.9 works very well too

**Comment by ErrorDoc404** [comment]
thanx
